name: Setup Devenv

runs:
  using: 'composite'
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v31

    - name: Install Cachix
      uses: cachix/cachix-action@v16
      with:
        name: devenv

    - name: Install devenv
      shell: bash
      run: nix profile install nixpkgs#devenv
